all:  multitable.pdf readingmultipletables.pdf
multitable.pdf : multitable.tex
	texi2dvi --pdf --clean multitable.tex
	-rm -f multitable-*.pdf
readingmultipletables.pdf : readingmultipletables.tex Bibliography.bib
	texi2dvi --pdf --clean readingmultipletables.tex
